# MTK Hardware
BOARD_USES_MTK_HARDWARE := true
TARGET_USES_ION := true
BOARD_GLOBAL_CFLAGS += -DADD_LEGACY_ACQUIRE_BUFFER_SYMBOL
BOARD_GLOBAL_CFLAGS += -DMTK_HARDWARE
BOARD_USE_SOFT_GATEKEEPER := true

# Graphics
OVERRIDE_RS_DRIVER := libRSDriver_mtk.so
